language: perl
perl:
    - 5.18

env:
    - VERSION="2.0"

before_install:
    - sudo apt-get install -qq python-software-properties
    - echo "yes" | sudo add-apt-repository "ppa:chris-lea/zeromq"
    - sudo apt-get update -qq
    - perl -V

install:
    - sudo apt-get install -y curl mailutils build-essential git-core automake cpanminus rng-tools openjdk-7-jre-headless libtool pkg-config vim htop bind9 libzmq3-dev libffi6 libmoose-perl libmouse-perl libanyevent-perl liblwp-protocol-https-perl libxml2-dev libexpat-dev python-dev
    - cpanm Regexp::Common
    - cpanm Net::Works::Address --force
    - cpanm --mirror http://cpan.metacpan.org --notest DateTime # workaround for https://github.com/csirtgadgets/massive-octo-spice/issues/131
    - cpanm http://backpan.perl.org/authors/id/M/MS/MSCHILLI/Log-Log4perl-1.44.tar.gz
    - cpanm https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Test-Exception-0.35.tar.gz
    - cpanm https://github.com/csirtgadgets/p5-cif-sdk/archive/master.tar.gz
    - cpanm https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/MaxMind-DB-Reader-0.050005.tar.gz
    - cpanm https://github.com/maxmind/GeoIP2-perl/archive/v0.040005.tar.gz
    - sudo rm -f /dev/random
    - sudo mknod -m 0666 /dev/random c 1 9
    - echo HRNGDEVICE=/dev/urandom | sudo tee /etc/default/rng-tools
    - sudo /etc/init.d/rng-tools restart

before_script:
    - bash autogen.sh

script:
    - ./configure && make
    - time make deps NOTESTS=-n
    - CI_BUILD=1 make test

notifications:
    email:
        on_success: never
        on_failure: always
branches:
    only:
        - master
        - staging
