language: perl
perl:
    - 5.18

before_install:
    - sudo apt-get install -qq python-software-properties
    - echo "yes" | sudo add-apt-repository "ppa:chris-lea/zeromq" 
    - sudo apt-get update -qq
    - perlbrew install-cpanm
    - perl -V

install:
    - sudo apt-get install -y curl mailutils build-essential git-core automake cpanminus rng-tools openjdk-7-jre-headless libtool pkg-config vim htop bind9 libzmq3-dev libffi6 libmoose-perl libmouse-perl libanyevent-perl liblwp-protocol-https-perl libxml2-dev libexpat-dev
    - cpanm Regexp::Common http://cpan.metacpan.org/CPAN/authors/id/S/SH/SHERZODR/Config-Simple-4.59.tar.gz http://cpan.metacpan.org/authors/id/N/NL/NLNETLABS/Net-DNS-0.76_2.tar.gz

before_script:
    - bash autogen.sh

script:
    - ./configure && make
    - time make deps NOTESTS=-n
    - CI_BUILD=1 make test 

notifications:
    email:
        on_success: never
        on_failure: always
branches:
    only:
        - master
        - /^release-.*$/
