language: perl
perl:
    - 5.18

before_install:
    - sudo apt-get install -qq python-software-properties
    - echo "yes" | sudo add-apt-repository "ppa:chris-lea/zeromq" 
    - sudo apt-get update -qq
    - perl -V

install:
    - sudo apt-get install -y curl mailutils build-essential git-core automake cpanminus rng-tools openjdk-7-jre-headless libtool pkg-config vim htop bind9 libzmq3-dev libffi6 libmoose-perl libmouse-perl libanyevent-perl liblwp-protocol-https-perl libxml2-dev libexpat-dev

before_script:
    - sh autogen.sh

script:
    - ./configure && make
    - time make deps NOTESTS=-n
    - CIF_PERL_NO_THREADS=1 make test 

notifications:
    email:
        on_success: never
        on_failure: always
branches:
    only:
        - master
        - /^release-.*$/
