FROM ubuntu
MAINTAINER Wes Young (wes@csirtgadgets.org)

RUN apt-get update && \
    apt-get install --no-install-recommends -y software-properties-common && \
    apt-add-repository ppa:ansible/ansible && \
    apt-get update && \
    apt-get install -y ansible

ADD ansible /srv/cifv2_base
WORKDIR /srv/cifv2_base

RUN ansible-playbook docker.yml -c local
