---

dependencies:
  - role: debops.etc_services
    etc_services_dependency_list:
      - name: 'elasticsearch-multicast'
        port: '{{ elasticsearch_discovery_multicast_port }}'

  - role: debops.java
    tags: java
    when: elasticsearch_role_dependencies is defined and
          'java' in elasticsearch_role_dependencies

galaxy_info:
  author: 'Gabriel Iovino'
  description: 'Install and manage Elasticsearch database clusters'
  company: 'CSIRT Gadgets'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.4.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - clustering
  - database
  - database:nosql
