---
# tasks file for cifv2

# Notes:

- name: Install needed software for cifv2
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
   - vim
   - htop
   - git
   - git-core
   - curl
   - pkg-config
   - rng-tools 
   - geoip-bin
   - starman 
   - python-dev
   - python-software-properties
   - software-properties-common
   - build-essential
   - automake
   - autoconf
   - libmodule-build-perl
   - libssl-dev
   - libtool
   - libffi6
   - libmoose-perl
   - libmouse-perl
   - libanyevent-perl
   - liblwp-protocol-https-perl
   - libxml2-dev
   - libexpat1-dev
   - libgeoip-dev

#- name: Test for cpanm
#  shell: perl -MApp::cpanminus -e1
#  register: cpanm_result
#  ignore_errors: True
#  tags: cpanmm

- name: Test for cpanm
  stat: path=/usr/local/bin/cpanm
  register: cpanm_result
  tags: cpanm

- name: Download and install cpnam
  shell: curl -L https://cpanmin.us | perl - App::cpanminus
  when: cpanm_result.stat.exists == False
  tags: cpanm

- name: "Download perl modules - ZMQx-Class, p5-cif-sdk, mojo"
  get_url: url={{ item }} dest=/tmp/
  with_items:
    - https://github.com/csirtgadgets/ZMQx-Class/archive/master.tar.gz
    - https://github.com/kraih/mojo/archive/v5.82.tar.gz
  tags: cpanm

- name: Install perl modules
  cpanm: name={{ item }} mirror=https://cpan.metacpan.org
  with_items:
    - Regexp::Common
    - HAARG/Moo-1.007000.tar.gz
    - GFUJI/Mouse-2.4.1.tar.gz
    - CALID/ZMQ-FFI-0.17.tar.gz
    - MSCHILLI/Log-Log4perl-1.44.tar.gz
    - ADIE/Test-Exception-0.32.tar.gz
    - DROLSKY/MaxMind-DB-Reader-0.050005.tar.gz
    - MAXMIND/GeoIP2-0.040005.tar.gz
    - AVAR/Hijk-0.19.tar.gz
    - DRTECH/Search-Elasticsearch-1.19.tar.gz
  tags: cpanm

- name: "Install perl modules - ZMQx-Class, p5-cif-sdk, mojo"
  cpanm: from_path={{ item.path }} notest={{ item.notest }}
  with_items:
    - { path: '/tmp/ZMQx-Class-master.tar.gz', notest: 'True' }
    - { path: '/tmp/mojo-5.82.tar.gz', notest: 'False' }
  tags: cpan
